import type { Metadata } from "next";
import CopyButton from "../../../components/CopyButton";
import PersistentLikeButton from "../../../components/PersistentLikeButton";
import Breadcrumbs from "../../../components/Breadcrumbs";
import StructuredData from "../../../components/StructuredData";
import quotesData from "../../../data/quotes";

export const dynamicParams = false;
export function generateStaticParams(){return quotesData.map((quote)=>({slug:quote.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const quote=quotesData.find((item)=>item.slug===slug);const isIndexable=quote?.indexable===true&&quote?.attributionStatus==="verified"&&quote?.copyrightStatus==="cleared";return{title:quote?`${quote.author}: “${quote.quote.slice(0,58)}${quote.quote.length>58?"…":""}” | Mayalines`:"Zitat | Mayalines",description:quote?.quote,alternates:quote?{canonical:`/quotes/${quote.slug}`} : undefined,robots:{index:isIndexable,follow:true}};}
export default async function QuotePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const quote=quotesData.find((item)=>item.slug===slug);if(!quote)return null;const siteUrl=process.env.NEXT_PUBLIC_SITE_URL||"https://mayalines.com";const quoteSchema={"@context":"https://schema.org","@type":"Quotation",text:quote.quote,creator:{"@type":"Person",name:quote.author},isPartOf:{"@type":"WebSite",name:"Mayalines",url:siteUrl}};return <main className="quote-detail"><Breadcrumbs items={[{name:"Startseite",url:"/"},{name:"Zitate",url:"/#main-content"},{name:quote.author,url:`/authors/${quote.author.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`}]} /><p className="eyebrow">{quote.category.toUpperCase()}</p><blockquote>“{quote.quote}”</blockquote><p className="quote-author">— {quote.author}</p><div className="quote-detail-actions"><PersistentLikeButton quoteId={quote.id} author={quote.author}/><CopyButton quote={quote.quote} author={quote.author}/></div><p className="source-note">Quelldatensatz: <a href={quote.source} rel="noreferrer">{quote.sourceName}</a></p><p className="source-note">Zuordnungsstatus: {quote.attributionStatus} · Veröffentlichungsstatus: {quote.copyrightStatus}</p><p className="source-note">Wenn du der Meinung bist, dass dieses Zitat falsch zugeordnet wurde oder entfernt werden sollte, findest du unter <a href="/copyright">Urheberrecht und Zitatkorrekturen</a> weitere Informationen.</p><StructuredData data={quoteSchema}/></main>;}
