"use client";
import { useEffect, useMemo, useState } from "react";
import quotesData from "../data/quotes";
type Item = { name: string; quote_id: string }; type Quote = (typeof quotesData)[number];
export default function LibraryDashboard() {
  const [items, setItems] = useState<Item[]>([]); const [recommendations, setRecommendations] = useState<Quote[]>([]); const [status, setStatus] = useState("Loading your library…");
  async function load() { const [library, suggested] = await Promise.all([fetch("/api/library", { cache: "no-store" }).then((r) => r.json()), fetch("/api/recommendations", { cache: "no-store" }).then((r) => r.json())]); setItems(library.collections ?? []); setRecommendations(suggested.quotes ?? []); setStatus(library.persistent ? "Saved with this browser’s private identifier." : "Library storage is not configured yet."); }
  useEffect(() => { const frame = window.requestAnimationFrame(() => { void load(); }); return () => window.cancelAnimationFrame(frame); }, []);
  const byId = useMemo(() => new Map(quotesData.map((quote) => [quote.id, quote])), []); const groups = useMemo(() => items.reduce<Record<string, Quote[]>>((all, item) => { const quote = byId.get(item.quote_id); if (quote) (all[item.name] ??= []).push(quote); return all; }, {}), [byId, items]);
  async function remove(quoteId: string, collection: string) { await fetch("/api/library", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "remove", quoteId, collection }) }); await load(); }
  return <main className="site-shell"><header className="header"><a className="brand" href="/"><span className="brand-name">MAYALINES</span></a><div className="header-rule"/><nav className="nav"><a href="/">Quotes</a><a href="/library" aria-current="page">My library</a><a href="/popular">Popular</a><a href="/trending">Trending</a></nav></header><section className="hero"><p className="eyebrow">MAYALINES · PERSONAL LIBRARY</p><h1>Your saved words.</h1><p className="hero-copy">Save quotes to Favorites, Read later or your own lists. Recommendations use only your saved quotes and follows in this browser.</p><p className="library-meta">{status}</p></section><section className="library"><div className="section-heading">Your lists</div>{Object.keys(groups).length ? Object.entries(groups).map(([name, quotes]) => <section key={name} style={{ marginTop: 30 }}><h2 className="library-meta">{name} · {quotes.length}</h2><div className="quote-grid">{quotes.map((quote) => <article className="quote-card" key={`${name}-${quote.id}`}><p className="quote-text">“{quote.quote}”</p><p className="quote-author">— {quote.author}</p><button className="copy-button" type="button" onClick={() => void remove(quote.id, name)}>REMOVE</button></article>)}</div></section>) : <p className="hero-copy">Save a quote from any quote card to start your library.</p>}</section><section className="library"><div className="section-heading">Recommended for you</div><p className="library-meta">Ranking basis: followed authors, followed topics and categories of saved quotes.</p>{recommendations.length ? <div className="quote-grid">{recommendations.map((quote) => <article className="quote-card" key={quote.id}><p className="quote-text">“{quote.quote}”</p><p className="quote-author">— {quote.author}</p><p className="quote-category">{quote.category}</p><a className="copy-button" href={`/quotes/${quote.slug}`}>VIEW QUOTE</a></article>)}</div> : <p className="hero-copy">Follow an author or topic, or save a quote to receive recommendations.</p>}</section><footer className="footer">© 2026 Mayalines</footer></main>;
}
