"use client";

import { useState } from "react";

const topics = [["Life","/topics/life"],["Love","/topics/love"],["Wisdom","/topics/wisdom"],["Success","/topics/success"],["Motivation","/topics/motivation"],["Happiness","/topics/happiness"],["Courage","/topics/courage"],["Friendship","/topics/friendship"],["Hope","/topics/hope"],["Philosophy","/topics/philosophy"],["Truth","/topics/truth"],["Inspiration","/topics/inspiration"]] as const;
const popularAuthors = [["William Shakespeare","/authors/william-shakespeare"],["Oscar Wilde","/authors/oscar-wilde"],["Friedrich Nietzsche","/authors/friedrich-nietzsche"],["Maya Angelou","/authors/maya-angelou"],["Albert Einstein","/authors/albert-einstein"],["Mark Twain","/authors/mark-twain"]] as const;
const collections = [["Quotes About Life","/collections/quotes-about-life"],["Quotes About Love","/collections/quotes-about-love"],["Quotes About Success","/collections/quotes-about-success"],["Motivational Quotes","/collections/quotes-about-motivation"],["Wisdom Quotes","/collections/quotes-about-wisdom"],["Short Inspirational Quotes","/collections/short-inspirational-quotes"]] as const;

export default function MegaMenu() {
  const [open, setOpen] = useState<string | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  function closeMenu() { setOpen(null); setMobileOpen(false); }
  const trigger = (name: string, label: string) => <button className="mega-trigger" type="button" aria-expanded={open === name} onMouseEnter={() => setOpen(name)} onFocus={() => setOpen(name)} onClick={() => setOpen(open === name ? null : name)}>{label} <span className="mega-chevron" aria-hidden="true">⌄</span></button>;

  return <>
    <style>{`.mega-desktop{display:flex;align-items:center;gap:19px}.mega-trigger{display:inline-flex;align-items:center;gap:5px;color:var(--muted);font-size:12px;font-weight:600;padding:8px 0}.mega-trigger:hover,.mega-trigger[aria-expanded="true"]{color:var(--brown)}.mega-chevron{font-size:9px;transition:transform .22s cubic-bezier(.2,.8,.2,1)}.mega-trigger[aria-expanded="true"] .mega-chevron{transform:rotate(180deg)}.mega-panel{position:absolute;z-index:80;top:76px;left:50%;right:auto;width:min(1180px,calc(100% - 56px));transform:translateX(-50%);padding:0 26px 26px;background:rgba(251,250,248,.97);border:1px solid #d7d3cc;border-top:0;border-radius:0 0 12px 12px;box-shadow:0 22px 55px rgba(23,21,19,.12);backdrop-filter:blur(18px);animation:mega-in .24s cubic-bezier(.2,.8,.2,1)}.mega-inner{padding:26px 0 0;display:grid;grid-template-columns:1.15fr 1.15fr 1fr 1fr;gap:30px}.mega-column{min-width:0}.mega-label{margin:0 0 13px;color:var(--brown);font-size:9px;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.mega-links{display:grid;gap:7px}.mega-links a{font-family:Georgia,"Times New Roman",serif;font-size:16px;line-height:1.2;color:var(--foreground);transition:color .18s ease,transform .18s ease}.mega-links a:hover{color:var(--brown);transform:translateX(4px)}.mega-feature{padding:17px 18px;background:#e9e5df;border:1px solid #d5d0c8;border-radius:8px;align-self:start}.mega-feature p{margin:0 0 10px;color:var(--muted);font-size:10px;line-height:1.55}.mega-feature a{color:var(--brown);font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.mega-mobile-button{display:none;color:var(--muted);font-size:11px;font-weight:750;letter-spacing:.06em;text-transform:uppercase;padding:8px 0}.mega-mobile{display:none}@keyframes mega-in{from{opacity:0;transform:translate(-50%,-10px) scale(.985)}to{opacity:1;transform:translate(-50%,0) scale(1)}}@media(max-width:900px){.mega-desktop{display:none}.mega-mobile-button{display:inline-flex}.mega-panel{position:fixed;top:0;left:0;right:0;bottom:0;width:auto;transform:none;overflow:auto;padding:88px 22px 28px;background:rgba(251,250,248,.98);border:0;border-radius:0;animation:mega-mobile-in .22s ease-out}.mega-inner{grid-template-columns:1fr 1fr;gap:28px 20px;padding:0}.mega-mobile{display:block}.mega-close{position:absolute;top:24px;right:22px;padding:10px 0;color:var(--brown);font-size:11px;font-weight:800;letter-spacing:.08em}.mega-panel .mega-label{margin-bottom:10px}.mega-links a{font-size:17px}}@media(max-width:560px){.mega-inner{grid-template-columns:1fr;gap:24px}.mega-panel{padding-left:18px;padding-right:18px}.mega-links{grid-template-columns:1fr 1fr;column-gap:18px}.mega-links a{font-size:16px}}@keyframes mega-mobile-in{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:translateY(0)}}`}</style>
    <div className="mega-desktop" onMouseLeave={() => setOpen(null)}>
      {trigger("quotes","Quotes")}{trigger("topics","Topics")}{trigger("authors","Authors")}{trigger("collections","Collections")}<a className="mega-trigger" href="/poems">Poems</a>
      {open && <div className="mega-panel" onMouseEnter={() => setOpen(open)}><div className="mega-inner">
        {open === "quotes" && <><div className="mega-column"><p className="mega-label">Discover</p><div className="mega-links"><a href="/popular">Popular Quotes</a><a href="/trending">Trending Quotes</a><a href="/most-copied">Most Copied</a><a href="/random">Random Quote</a><a href="/">Quote Library</a></div></div><div className="mega-column"><p className="mega-label">By Type</p><div className="mega-links"><a href="/collections/short-inspirational-quotes">Short Quotes</a><a href="/collections/quotes-about-love">Love Quotes</a><a href="/collections/quotes-about-life">Life Quotes</a><a href="/collections/quotes-about-success">Success Quotes</a></div></div><div className="mega-column"><p className="mega-label">Explore</p><div className="mega-links"><a href="/topics">All Topics</a><a href="/authors">All Authors</a><a href="/collections">All Collections</a><a href="/submit">Submit a Quote</a></div></div><div className="mega-feature"><p>Find memorable words by author, topic, popularity or recent community activity.</p><a href="/most-copied">Explore most copied →</a></div></>}
        {open === "topics" && <><div className="mega-column"><p className="mega-label">Popular Topics</p><div className="mega-links">{topics.slice(0,6).map(([label,url])=><a key={url} href={url}>{label}</a>)}</div></div><div className="mega-column"><p className="mega-label">More Topics</p><div className="mega-links">{topics.slice(6).map(([label,url])=><a key={url} href={url}>{label}</a>)}</div></div><div className="mega-column"><p className="mega-label">Collections</p><div className="mega-links"><a href="/collections/quotes-about-life">Life Quotes</a><a href="/collections/quotes-about-love">Love Quotes</a><a href="/collections/quotes-about-wisdom">Wisdom Quotes</a><a href="/collections/quotes-about-motivation">Motivation</a></div></div><div className="mega-feature"><p>Browse the full topic directory and discover quotes by theme.</p><a href="/topics">View all topics →</a></div></>}
        {open === "authors" && <><div className="mega-column"><p className="mega-label">Popular Authors</p><div className="mega-links">{popularAuthors.map(([label,url])=><a key={url} href={url}>{label}</a>)}</div></div><div className="mega-column"><p className="mega-label">Browse</p><div className="mega-links"><a href="/authors">All Authors</a><a href="/popular">Most Popular Quotes</a><a href="/most-copied">Most Copied Quotes</a><a href="/trending">Trending Quotes</a></div></div><div className="mega-column"><p className="mega-label">Also Explore</p><div className="mega-links"><a href="/topics">Topics</a><a href="/collections">Collections</a><a href="/poems">Poems</a><a href="/submit">Submit a Quote</a></div></div><div className="mega-feature"><p>Explore quotes from writers, thinkers and cultural figures.</p><a href="/authors">Browse all authors →</a></div></>}
        {open === "collections" && <><div className="mega-column"><p className="mega-label">Featured Collections</p><div className="mega-links">{collections.slice(0,3).map(([label,url])=><a key={url} href={url}>{label}</a>)}</div></div><div className="mega-column"><p className="mega-label">More Collections</p><div className="mega-links">{collections.slice(3).map(([label,url])=><a key={url} href={url}>{label}</a>)}</div></div><div className="mega-column"><p className="mega-label">Discover</p><div className="mega-links"><a href="/popular">Popular Quotes</a><a href="/most-copied">Most Copied</a><a href="/trending">Trending Quotes</a><a href="/topics">Browse Topics</a></div></div><div className="mega-feature"><p>Curated collections built around themes and search intent.</p><a href="/collections">View all collections →</a></div></>}
      </div></div>}
    </div>
    <button className="mega-mobile-button" type="button" aria-expanded={mobileOpen} onClick={() => setMobileOpen(true)}>Menu +</button>
    {mobileOpen && <div className="mega-panel mega-mobile"><button className="mega-close" type="button" onClick={closeMenu}>CLOSE ×</button><div className="mega-inner"><div className="mega-column"><p className="mega-label">Quotes</p><div className="mega-links"><a href="/popular" onClick={closeMenu}>Popular Quotes</a><a href="/trending" onClick={closeMenu}>Trending Quotes</a><a href="/most-copied" onClick={closeMenu}>Most Copied</a><a href="/random" onClick={closeMenu}>Random Quote</a><a href="/" onClick={closeMenu}>Quote Library</a></div></div><div className="mega-column"><p className="mega-label">Topics</p><div className="mega-links">{topics.map(([label,url])=><a key={url} href={url} onClick={closeMenu}>{label}</a>)}</div></div><div className="mega-column"><p className="mega-label">Authors</p><div className="mega-links">{popularAuthors.map(([label,url])=><a key={url} href={url} onClick={closeMenu}>{label}</a>)}<a href="/authors" onClick={closeMenu}>All Authors →</a></div></div><div className="mega-column"><p className="mega-label">Collections</p><div className="mega-links">{collections.map(([label,url])=><a key={url} href={url} onClick={closeMenu}>{label}</a>)}<a href="/collections" onClick={closeMenu}>All Collections →</a></div></div><div className="mega-column"><p className="mega-label">More</p><div className="mega-links"><a href="/poems" onClick={closeMenu}>Famous Poems</a><a href="/submit" onClick={closeMenu}>Submit a Quote</a><a href="/most-copied" onClick={closeMenu}>Most Copied Quotes</a></div></div></div></div>}
  </>;
}
